/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secondAssignment.system.ui;

/**
 *
 * @author sweta
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminbtn2 = new javax.swing.JButton();
        adminbtn = new javax.swing.JButton();
        adminbtn3 = new javax.swing.JButton();
        adminbtn1 = new javax.swing.JButton();
        adminbtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminbtn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminbtn2.setForeground(new java.awt.Color(51, 153, 255));
        adminbtn2.setText("System Admin");
        adminbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminbtn2MouseClicked(evt);
            }
        });
        adminbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn2ActionPerformed(evt);
            }
        });

        adminbtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminbtn.setForeground(new java.awt.Color(51, 153, 255));
        adminbtn.setText("Hospital Admin");
        adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnActionPerformed(evt);
            }
        });

        adminbtn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminbtn3.setForeground(new java.awt.Color(51, 153, 255));
        adminbtn3.setText("Doctor");
        adminbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn3ActionPerformed(evt);
            }
        });

        adminbtn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminbtn1.setForeground(new java.awt.Color(51, 153, 255));
        adminbtn1.setText("Patient");
        adminbtn1.setToolTipText("Hospital Admin");
        adminbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn1ActionPerformed(evt);
            }
        });

        adminbtn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminbtn4.setForeground(new java.awt.Color(51, 153, 255));
        adminbtn4.setText("Community Admin");
        adminbtn4.setToolTipText("");
        adminbtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminbtn4MouseClicked(evt);
            }
        });
        adminbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(adminbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(adminbtn4)
                .addGap(63, 63, 63)
                .addComponent(adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(adminbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(adminbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(325, 325, 325))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminbtn2MouseClicked
        ////Adminlogin a=new Adminlogin();
        //a.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_adminbtn2MouseClicked

    private void adminbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbtn2ActionPerformed

    private void adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnActionPerformed
        //       //ReceptionistLogin rl=new ReceptionistLogin();
        //       rl.setVisible(true);
        //       this.dispose();
    }//GEN-LAST:event_adminbtnActionPerformed

    private void adminbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn3ActionPerformed
        //doctorlogin dl=new doctorlogin();
        //dl.setVisible(true);
        //this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_adminbtn3ActionPerformed

    private void adminbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn1ActionPerformed
        //  medicinedetails1 ma=new medicinedetails1();
        //        ma.setVisible(true);
        //        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbtn1ActionPerformed

    private void adminbtn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminbtn4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbtn4MouseClicked

    private void adminbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbtn;
    private javax.swing.JButton adminbtn1;
    private javax.swing.JButton adminbtn2;
    private javax.swing.JButton adminbtn3;
    private javax.swing.JButton adminbtn4;
    // End of variables declaration//GEN-END:variables
}
