/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firstassignment;

/**
 *
 * @author sweta
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainForm = new javax.swing.JPanel();
        sidePannel = new javax.swing.JPanel();
        bEmpIcon = new javax.swing.JLabel();
        bEmpName = new javax.swing.JLabel();
        bEmpDesignation = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn18 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn19 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn21 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn22 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn23 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btn24 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btn25 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btn26 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btn27 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btn28 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btn29 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btn30 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btn31 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btn32 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btn33 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btn34 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        btn35 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btn36 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btn37 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btn38 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btn39 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btn40 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btn41 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePannel.setBackground(new java.awt.Color(255, 51, 0));
        sidePannel.setPreferredSize(new java.awt.Dimension(120, 600));
        sidePannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bEmpIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bEmpIcon.setToolTipText("");
        bEmpIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidePannel.add(bEmpIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 147, 170));

        bEmpName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bEmpName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bEmpName.setText("EmpName");
        sidePannel.add(bEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 147, 30));

        bEmpDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bEmpDesignation.setText("EmpDesignation");
        sidePannel.add(bEmpDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, 147, 20));

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log Out");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn7.setBackground(new java.awt.Color(0, 0, 0));
        btn7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dash Board");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn5.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        btn8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dash Board");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn9.setBackground(new java.awt.Color(0, 0, 0));
        btn9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dash Board");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn8.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn5.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn14.setBackground(new java.awt.Color(0, 0, 0));
        btn14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Employee");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn14.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn15.setBackground(new java.awt.Color(0, 0, 0));
        btn15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Dash Board");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn14.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn16.setBackground(new java.awt.Color(0, 0, 0));
        btn16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Dash Board");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn17.setBackground(new java.awt.Color(0, 0, 0));
        btn17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Dash Board");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn17.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn16.add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn14.add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn5.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));

        sidePannel.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 150, 50));

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Profile");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        sidePannel.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 223, 150, 50));

        btn10.setBackground(new java.awt.Color(0, 0, 0));
        btn10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dash Board");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn11.setBackground(new java.awt.Color(0, 0, 0));
        btn11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dash Board");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn10.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn12.setBackground(new java.awt.Color(0, 0, 0));
        btn12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dash Board");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn13.setBackground(new java.awt.Color(0, 0, 0));
        btn13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dash Board");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn12.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn10.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        sidePannel.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn18.setBackground(new java.awt.Color(0, 0, 0));
        btn18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Employee");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn18.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn19.setBackground(new java.awt.Color(0, 0, 0));
        btn19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Dash Board");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn19.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn18.add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn20.setBackground(new java.awt.Color(0, 0, 0));
        btn20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Dash Board");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn20.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn21.setBackground(new java.awt.Color(0, 0, 0));
        btn21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Dash Board");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn21.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn20.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn18.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn22.setBackground(new java.awt.Color(0, 0, 0));
        btn22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Employee");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn22.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn23.setBackground(new java.awt.Color(0, 0, 0));
        btn23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Dash Board");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn23.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn22.add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn24.setBackground(new java.awt.Color(0, 0, 0));
        btn24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Dash Board");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn24.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn25.setBackground(new java.awt.Color(0, 0, 0));
        btn25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Dash Board");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn25.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn24.add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn22.add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn18.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));

        sidePannel.add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));

        btn26.setBackground(new java.awt.Color(0, 0, 0));
        btn26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Salary");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn26.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn27.setBackground(new java.awt.Color(0, 0, 0));
        btn27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Dash Board");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn27.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn26.add(btn27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn28.setBackground(new java.awt.Color(0, 0, 0));
        btn28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Dash Board");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn28.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn29.setBackground(new java.awt.Color(0, 0, 0));
        btn29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Dash Board");
        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn29.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn28.add(btn29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn26.add(btn28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn30.setBackground(new java.awt.Color(0, 0, 0));
        btn30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Employee");
        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn30.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn31.setBackground(new java.awt.Color(0, 0, 0));
        btn31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Dash Board");
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn31.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn30.add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn32.setBackground(new java.awt.Color(0, 0, 0));
        btn32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Dash Board");
        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn32.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn33.setBackground(new java.awt.Color(0, 0, 0));
        btn33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Dash Board");
        jLabel29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn33.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn32.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn30.add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn26.add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));

        sidePannel.add(btn26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        btn34.setBackground(new java.awt.Color(0, 0, 0));
        btn34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Leave");
        jLabel30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn34.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn35.setBackground(new java.awt.Color(0, 0, 0));
        btn35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Dash Board");
        jLabel31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn35.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn34.add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn36.setBackground(new java.awt.Color(0, 0, 0));
        btn36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Dash Board");
        jLabel32.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn36.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn37.setBackground(new java.awt.Color(0, 0, 0));
        btn37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Dash Board");
        jLabel33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn37.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn36.add(btn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn34.add(btn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn38.setBackground(new java.awt.Color(0, 0, 0));
        btn38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Employee");
        jLabel34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn38.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn39.setBackground(new java.awt.Color(0, 0, 0));
        btn39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Dash Board");
        jLabel35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn39.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn38.add(btn39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn40.setBackground(new java.awt.Color(0, 0, 0));
        btn40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Dash Board");
        jLabel36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn40.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn41.setBackground(new java.awt.Color(0, 0, 0));
        btn41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Dash Board");
        jLabel37.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        btn41.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        btn40.add(btn41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn38.add(btn40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        btn34.add(btn38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));

        sidePannel.add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 150, 50));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("edhar kuch chahiye");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        headerPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 0, 74, 49));

        javax.swing.GroupLayout mainFormLayout = new javax.swing.GroupLayout(mainForm);
        mainForm.setLayout(mainFormLayout);
        mainFormLayout.setHorizontalGroup(
            mainFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFormLayout.createSequentialGroup()
                .addComponent(sidePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainFormLayout.setVerticalGroup(
            mainFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFormLayout.createSequentialGroup()
                .addGroup(mainFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bEmpDesignation;
    private javax.swing.JLabel bEmpIcon;
    private javax.swing.JLabel bEmpName;
    private javax.swing.JPanel btn10;
    private javax.swing.JPanel btn11;
    private javax.swing.JPanel btn12;
    private javax.swing.JPanel btn13;
    private javax.swing.JPanel btn14;
    private javax.swing.JPanel btn15;
    private javax.swing.JPanel btn16;
    private javax.swing.JPanel btn17;
    private javax.swing.JPanel btn18;
    private javax.swing.JPanel btn19;
    private javax.swing.JPanel btn20;
    private javax.swing.JPanel btn21;
    private javax.swing.JPanel btn22;
    private javax.swing.JPanel btn23;
    private javax.swing.JPanel btn24;
    private javax.swing.JPanel btn25;
    private javax.swing.JPanel btn26;
    private javax.swing.JPanel btn27;
    private javax.swing.JPanel btn28;
    private javax.swing.JPanel btn29;
    private javax.swing.JPanel btn30;
    private javax.swing.JPanel btn31;
    private javax.swing.JPanel btn32;
    private javax.swing.JPanel btn33;
    private javax.swing.JPanel btn34;
    private javax.swing.JPanel btn35;
    private javax.swing.JPanel btn36;
    private javax.swing.JPanel btn37;
    private javax.swing.JPanel btn38;
    private javax.swing.JPanel btn39;
    private javax.swing.JPanel btn40;
    private javax.swing.JPanel btn41;
    private javax.swing.JPanel btn5;
    private javax.swing.JPanel btn6;
    private javax.swing.JPanel btn7;
    private javax.swing.JPanel btn8;
    private javax.swing.JPanel btn9;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainForm;
    private javax.swing.JPanel sidePannel;
    // End of variables declaration//GEN-END:variables
}
